version: '3.9'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: joresduona
      POSTGRES_PASSWORD: joresduona
      POSTGRES_DB: joresduona
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local